"""
Configuration modules for Gemini CLI MCP Server
"""
from .gemini_config import (
    GEMINI_TIMEOUT,
    GEMINI_PROMPT_LIMIT,
    GEMINI_SANDBOX_LIMIT,
    GEMINI_SUMMARIZE_LIMIT,
    GEMINI_SUMMARIZE_FILES_LIMIT,
    GEMINI_EVAL_LIMIT,
    GEMINI_REVIEW_LIMIT,
    GEMINI_VERIFY_LIMIT,
    GEMINI_COLLABORATION_LIMIT,
    DEFAULT_MODEL,
    FALLBACK_MODEL,
    get_model_scaling_factor,
)
